# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0-beta.2"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0-beta.2"

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

[[constraint]]
  name = "gopkg.in/d4l3k/messagediff.v1"
  revision = "b9e99b2f9263a86c71c1ca4507f34502448c58a4"


[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  branch = "master"

[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.27.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.13.0"

[[constraint]]
  name = "google.golang.org/api"
  version = "v0.3.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"
